### ISSUE TITLE
Mob Spawning

### ISSUE THREAD

**Issue by austin-wiechman** [CompactMods/CompactMachines#296] opened 2018-01-19 22:07 UTC
I have several mob farms in compact machines. One with an Industrial Foregoing Mob Duplicator, and the other with an Extra Utils 2 spawner. Both work perfectly fine when I am in the machine, but both stop spawning when I leave, any clue why this might be?

**Comment by austin-wiechman** [comment] 2018-01-21 19:22
Anyone?

**Comment by davenonymous** [comment] 2018-01-21 19:35
You are not specific enough. Please provide more details.
For all I know you've disabled chunk loading of machines.

**Comment by austin-wiechman** [comment] 2018-01-22 23:03
Sorry about that. Chunk loading is not disabled (Unless it is that way by default). The config had not been tampered with in any way when the issue first came up. Since then the only thing that has been changed is the option to force chunk loading as a test to see if that would solve the issue (it didn't).

Basically what I am trying to do, is create a compact machine that produces nether stars. To accomplish this goal I have several nested machines. The bottom layer used to have cursed earth, but has since been replaced with a Resturbed Mob Spawner. The mobs spawned by this are killed by the Industrial Foregoing Mob Crusher, which voids the items and exports the mob essence. The next level uses the mob essence in a Mob Duplicator from Industrial Foregoing to spawn Wither Skeletons, which are killed in the same manner as the previous level, recycling the mob essence and exporting the skulls. Finally, the skulls are combined with soul sand to spawn the Withers. Unfortunately, neither of the two above mentioned mob spawners work when I am not present in the machine and I cannot determine why.

I would assume the issue is related to chunk loading in some way, but I cannot determine how and was hoping someone else could help me figure it out.

**Comment by austin-wiechman** [comment] 2018-01-25 21:30
Was that not enough information?

**Comment by davenonymous** [comment] 2018-01-25 21:53
I got other things to do as well, please have patience. There is no need to bump an issue. If it's not closed I will take a look at it sooner or later. Regarding how to report bugs, vazkii has an excellent guide [here](https://vazkii.us/br101/).

That being said, it definitely looks like a chunk loading issue. Your machines are nested, you say? Just to make sure it's actually a chunk loading issue, can you place a spot loader or use some other means to load the machine chunks having issues? Does that resolve it?

I was not able to reproduce such issues in the past and expect some other interference with another mods chunk loading. What other mods are you running that have something to do with chunk loading?

**Comment by austin-wiechman** [comment] 2018-01-25 22:03
Sorry, I was not sure if you had just not gotten around to my issue or if I still needed more information. Spot loaders don't seem to work either. The only mods that I have installed that I know chunk load are Compact Machines, Chicken Chunks, Open Computers, and Extra Utilities (Quarry). I believe that is it.

**Comment by WilliamBlaze** [comment] 2018-05-03 17:16
could it be something in one of those other chunk loading options that is interfering with the chunk load process of Compact machines? Extra Utilities and chicken chunks i've ran side by side with compact machines in the past without any issues; so might i suggest checking the configs for Open Computers? i know they have a feature that keeps certain chunks loaded while your in the world but otherwise deactivates them when your off in another dimension. If i had to take a guess this could be causing some minor conflicts with Compact machines in that its overriding CM's chunk loaded features/options. if you get the chance Go-Wish; try checking out your Open Computers configurations and see if there's a chunk based option floating about; edit it from its current setting and let us know your results. If this fixes the issue then cool; if not; i guess thraaawn will still need to look into this one.

**Comment by robotgryphon** [comment] 2021-01-16 01:51
Lack of information on which version(s) are affected and no recent comments indicating this is still an issue in b278. Closing until verified on the latest version.

**Closed as completed by robotgryphon** 2021-01-16 01:51 UTC
Labels: unverified
