### ISSUE TITLE
Furnace reset when leaving and entering a CM

### ISSUE THREAD

**Issue by EddyBuhler** [CompactMods/CompactMachines#504] opened 2022-02-01 07:49 UTC
### I am not using performance mods.

- [x] Confirm

### Description

The furnace status is not correctly saved on leaving/re-entering a compact machine on the latest version for minecraft 1.18.1

### Mod Version

compactmachines-4.0.0-beta.4.jar

### Forge Version

1.18.1-forge-39.0.64

### How to reproduce

1. I put a stack of items in a furnace inside a CM. 
2. I wait until a few items are done smelting, but do not take them out or interact with the furnace. 
3. I then proceed to leave the CM, e.g. at 4 items smelted
4. I wait a minute right outside the CM
5. I re-enter the CM. 

Expected behavior: more than 4 items have been smelted inside the furnace.

Actual behavior: the furnace is reset, the stack to smelt is again at 64 items, the output is empty again

If I remove items from the furnace output, that change is saved.

I also use Terralith 2.0 in case that messes with dimensions/saving the CM state correctly.

**Comment by robotgryphon** [comment] 2022-02-01 07:55
Seems the chunk isn't being persisted/saved correctly. Likely related to chunkloading. Will be able to investigate alongside tunnel work.

**Comment by EddyBuhler** [comment] 2022-02-01 08:04
I also noticed that sleeping in a bed inside a CM does not advance the time in the overworld. Not sure if this is related or working as intended.

**Comment by robotgryphon** [comment] 2022-06-01 04:31
Closing this; working as intended with latest versions.

**Closed as not planned by robotgryphon** 2022-06-01 04:31 UTC
Labels: 18.x, cannot-reproduce
