### ISSUE TITLE
Wrong Warp / Misbehaving New Machine Registration

### ISSUE THREAD

**Issue by Tankenheimer** [CompactMods/CompactMachines#513] opened 2022-04-26 23:55 UTC
### I am not using performance mods.

- [X] Confirm

### Description

I crafted and attempted to enter a 9x9 compact machine on a public server, but was instead placed inside another player's 13x13 compact machine.  I have broken, replaced, and attempted to re-enter my machine several times, but always end up in the other player's machine instead.

### Mod Version

4.2.0

### Forge Version

1.18.2 - 40.1.0

### How to reproduce

1.  Placed a 9x9 compact machine block
2.  Right clicked with personal shrinking device
3.  Spawned into other player's 13x13 compact machine

**Comment by PmanAce** [comment] 2022-04-30 17:05
Same issue for me (ATM7). Crafted all the different sizes and 4 of them enter the 9x9 one. As a test I added a spawn point in the corner and those 4 all spawn to that corner.

**Comment by Light2Blue2** [comment] 2022-05-07 20:27
Same thing for me to, also doing ATM7, placed my reactor in a 13x13 and left it to get some pipes but everytime i go inside it puts me in my 9x9, replaced the 13x13, reloaded game, and moved it and still puts me in my 9x9, if its not fixable then thatd really suc bc i put the whole reactor in there xD

**Comment by robotgryphon** [comment] 2022-05-08 12:28
Potentially closed with nightly 4.2.0.11. Will keep this open until v4.3.0 drops.

**Comment by derrickmehaffy** [comment] 2022-05-11 04:05
> Potentially closed with nightly 4.2.0.11. Will keep this open until v4.3.0 drops.

Can you link the PR that you believe fixes this? Just curious to take a look at the code behind the fix.

**Comment by robotgryphon** [comment] 2022-05-11 04:38
> > Potentially closed with nightly 4.2.0.11. Will keep this open until v4.3.0 drops.
> 
> Can you link the PR that you believe fixes this? Just curious to take a look at the code behind the fix.

Part of https://github.com/CompactMods/CompactMachines/commit/e5c21eceff4443d500fe0b4d3f839a01f19dd933, which is part of a greater overhaul to work towards entangled machines. Machine blocks will drop with the room location rather than an ID after this commit, and free up the ID for future assignment. Placement of the machine afterward picks the first available ID to use.

**Comment by derrickmehaffy** [comment] 2022-05-12 17:42
> > > Potentially closed with nightly 4.2.0.11. Will keep this open until v4.3.0 drops.
> > 
> > 
> > Can you link the PR that you believe fixes this? Just curious to take a look at the code behind the fix.
> 
> Part of [e5c21ec](https://github.com/CompactMods/CompactMachines/commit/e5c21eceff4443d500fe0b4d3f839a01f19dd933), which is part of a greater overhaul to work towards entangled machines. Machine blocks will drop with the room location rather than an ID after this commit, and free up the ID for future assignment. Placement of the machine afterward picks the first available ID to use.

Ahhh alright fantastic, thank you :)

**Comment by robotgryphon** [comment] 2022-05-28 05:15
See release notes for v4.3.0, should close this issue. Please reach out on Discord or reopen the issue if the problem is not resolved.

**Closed as completed by robotgryphon** 2022-05-28 05:15 UTC
Labels: verified, 18.x
