### ISSUE TITLE
Cannot place Parabox inside Compact Machine in Sky Factory 4

### ISSUE THREAD

**Issue by Xuhybrid** [CompactMods/CompactMachines#394] opened 2019-04-28 17:33 UTC
**Compact Machines version**:3.0.17-b267
**Forge version**:forge-14.23.5.2831
**I am not using Optifine**:not using

**Description of the problem including expected versus actual behavior:**
In SkyFactory 4 Compactsky when placing a Parabox inside a Compact Machine, i receive the following error: "a temporal anomaly prevents placing this here". This effectively destroys the entire Prestige system on this island type and disables the progression system.

**Steps to reproduce:**
Open SkyFactory 4 (4.0.3)
Create new world with Compactsky preset and Prestige enabled
Place Parabox inside compact machine

I apologise if this is a problem caused by the pack creator or Parabox mod author. There is a post up on SF4 issue tracker about the same issue here: https://github.com/Darkosto/SkyFactory4Issues/issues/478

**Comment by robotgryphon** [comment] 2021-01-16 02:58
Going to close this one due to it referencing an older version of CM3, and the likely possibility this is an issue with Parabox and the Compact Sky dimension's time configuration. If both of the mods on their latest version cause a conflict, please reopen -- will need to look into Parabox's source to find the root cause.

**Closed as completed by robotgryphon** 2021-01-16 02:58 UTC
Labels: unverified
