### ISSUE TITLE
[1.10.2] Crashing after server restart

### ISSUE THREAD

**Issue by YOYOK9** [CompactMods/CompactMachines#204] opened 2017-05-19 15:22 UTC
Started a new server world and after switching from a batch file start to using amp to start it I get this crash on startup:
https://pastebin.com/whiLLq7X

cm2: 2.0.0-b104
Forge: 1.10.2-12.18.3.2297-universal
Sponge: 1.10.2-2281-5.2.0-BETA-2341
mc: 1.10.2

**Comment by davenonymous** [comment] 2017-05-20 10:21
Duplicate of #203

**Closed as completed by davenonymous** 2017-05-20 10:21 UTC
