### ISSUE TITLE
Shimmering textures. The problem with energy is 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [CompactMods/CompactMachines#349] opened 2018-07-27 14:04 UTC
Sometimes the texture begins to flicker after entering / exiting the CM.
The energy of the engines from the BuildCraft does not always enter / exit.

**Compact Machines version**: 3.0.12-B215
**Forge version**: Spongeforge-1.12.2-2705-7.1.0-BETA-3350
**Minecraft**: 1.12.2

**Comment by davenonymous** [comment] 2018-07-27 14:21
Future bug reporting tips:
Be kind to the developer you are reporting problem to and don't make them not want to resolve your issue. This includes for example:
- Create one issue per problem, never put two problems in one issue unless otherwise told to by the dev (or devteam) himself.
- Be precise and follow the guidelines outlined in an issue template. If you skipped steps at least explain why you skipped those steps. If it says to read something, read it.

Regarding your both issues.
Which texture? You have to be a lot more precise for me to be able to help you. Please try with the latest build from [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0), then create a new issue for this if it's not yet resolved.
Regarding energy: as long as Buildcraft is not using Forge Capabilities there is not much I can/want to do about it - or in other words: if a mod does not work via tunnels, it's because they did not implement some of their features using Forge Capabilities, but classic Java interfaces instead.

**Comment by xxxLEOPARDxxx** [comment] 2018-07-27 15:14
I apologize for what I began to describe not by points or by rules.
I downloaded it and I'll test it. If the problem persists, then I'll write down the points as you ask.
By the way, I corrected the file of Russian localization. There was a problem in displaying the numbering mechanism.
https://drive.google.com/open?id=1uHp6EUNpMLDpWWQdMRyKXAv6kbThhMi0
This is a corrected localization file.

**Comment by xxxLEOPARDxxx** [comment] 2018-08-02 20:30
Flickering of textures begins after they have entered / left the fields from the spotlights. Below is a link to the video where the flicker is shown.
https://i.gyazo.com/ca75de9d11e43ff6275085385094c69f.mp4

**Comment by davenonymous** [comment] 2018-08-03 13:50
Thanks, that helps. I will look into it soon!

**Comment by robotgryphon** [comment] 2021-01-16 17:52
I'm going to close this one due to being a report for an older version of the mod, and for having multiple issues in one ticket. If there's a world where this can be reproduced with the latest build, more than happy to look into this for final bugfixes on 1.12.

**Closed as completed by robotgryphon** 2021-01-16 17:52 UTC
