### ISSUE TITLE
JEID: Machine Preview is all *ite forms of stone

### ISSUE THREAD

**Issue by R93950X** [CompactMods/CompactMachines#409] opened 2019-08-18 20:02 UTC
Compact Machines version: compactmachines3-1.12.2-3.0.18-b278
Forge version: forge-14.23.5.2838
I am not using Optifine
https://media.discordapp.net/attachments/344165687603757056/612728266502963270/unknown.png?width=1052&height=702
https://media.discordapp.net/attachments/344165687603757056/612730027498405901/unknown.png

I expect to see the inside of the machine, instead i see the *ite forms of stone

Steps to reproduce: 
Install JEID&Compact machines
Install other mods
Place modded blocks in compact machine
View compact machine via GUI

**Comment by davenonymous** [comment] 2019-09-04 16:22
Duplicate of #357

**Closed as completed by davenonymous** 2019-09-04 16:22 UTC
