### ISSUE TITLE
[1.12] Crash when importing items

### ISSUE THREAD

**Issue by MrDj200** [CompactMods/CompactMachines#223] opened 2017-09-07 04:31 UTC
Hey o/
It's me again.

I got a crash.
It happened when I tried to pipe an item into the CM but inside the CM was nothing to retrieve it.
Maybe I should report this on thermal Expansions side (?)
Anyways:

MC Version: 1.12
Forge Version: 2443
CM Version: b125
Crash: https://pastebin.com/xL5RfNVV

Note: When restarting the server, it crashes again with the same exceptions.
Well, I already had to use MCEdit today, so its still installed yay.

P.S.: When it's on thermal Expansions/Dynamics side, tell me. Then I'll head over there :)

**Comment by davenonymous** [comment] 2017-09-07 05:12
Oh, that sounds bad.
I have an idea what it could be and will push a fix in a minute.
Currently at work, so I can't test it myself and will have to look into it further once i'm back.

**Comment by davenonymous** [comment] 2017-09-07 05:20
Could you retest that with the latest build b128 from [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0) please?

**Comment by MrDj200** [comment] 2017-09-07 05:26
Server Crashed again.
Report looks a bit different now: https://pastebin.com/KtqXRuQ4

**Comment by davenonymous** [comment] 2017-09-07 05:35
:disappointed: I'll look into it later today. Got to reproduce this in my development environment.

**Comment by MrDj200** [comment] 2017-09-07 05:36
okay. I'll test it with other item pipes. If it won't crash then, it's not your fault :P

**Comment by MrDj200** [comment] 2017-09-07 06:06
oh, in SP it gave another error. This time even from CM
https://pastebin.com/knra7dgi

And to correct myself:
I have an Itemduct inputting in the CM and inside the CM I have an Itemduct aswell. Just connected to the wall plug

**Comment by davenonymous** [comment] 2017-09-07 14:23
I can reproduce this easily. And it's really weird.
I don't think this is an issue on my end, @KingLemming, @rwtema.

I think what's happening here is Itemducts getting confused by not being in actual proximity to the Itemduct they are exporting items to. In fact, the two Itemducts interacting with each other are in two different dimensions. The Tunnel Block the Itemduct is actually connected to just passes along the capabilities provided by the other Itemduct outside the Machine Block.

Edit: What also might be causing the issue is EnumFacing of the capability changes, e.g. the itemduct thinks its pushing items into the west side, but the tunnel might actually be returning the capabilities of the block above it. ... just tried to verify this by keeping the sides intact, still crashes. EnumFacing isn't it.

**Comment by davenonymous** [comment] 2017-09-07 15:25
It looks like this has already been fixed in recent versions of Thermal Dynamics.
I can not reproduce this issue with the latest versions anymore. It works quite well actually...

I guess we're now even @MrDj200 💩

**Closed as completed by davenonymous** 2017-09-07 15:25 UTC

**Comment by MrDj200** [comment] 2017-09-07 20:49
Thanks. Gotta tell my players now how to update again...
^^
