### ISSUE TITLE
After started using the Compact Machines in the ATM 6 modpack my world is getting a lot of crashes and i cant load into it

### ISSUE THREAD

**Issue by umotakuretardado** [CompactMods/CompactMachines#443] opened 2021-01-15 21:25 UTC
**Compact Machines version**:4.0.0 alpha
**Forge version**: 35.1.29
**I am not using Optifine**: I'm using it, but i've tested without and the problem persists
**Link to Crashlog**: https://pastebin.com/hDH98GLL
**Screenshot (if possible)**: [here](url)
There isnt, the game just crashes
**Description of the problem including expected versus actual behavior:**
I was playing the modpack All The Mods 6 as usual, and started using the mod. Just after I started using, i got a crash and couldnt get in my world again, so re installed the pack (maybe to a newer version) and it worked. Now after 1-2 days, when trying to get in the world, the game just crashes. Tried without the mod and worked fine.
**Steps to reproduce:**
I dont know if its only my problem, but the only thing i do is try opening the world and the game crashes

**Comment by robotgryphon** [comment] 2021-01-16 01:59
Appears to be a duplicate of #438 - where dimension information is not properly loaded, causing null issues on the server side.

**Closed as completed by robotgryphon** 2021-01-16 01:59 UTC
Labels: 16.x
