### ISSUE TITLE
No valid recipe found when trying to craft the mini blocks

### ISSUE THREAD

**Issue by deceet** [CompactMods/CompactMachines#272] opened 2017-12-06 20:33 UTC
I have cm3 on my 1.12.2 server, and I can't get the field projectors to recognize the block of iron+redstone.

**Comment by davenonymous** [comment] 2017-12-06 20:38
Probably a duplicate of #271.
If it isn't, you'll need to be more specific. "It doesn't work" does not help anyone.

**Comment by deceet** [comment] 2017-12-06 20:42
No, I had made that initial mistake as well, I increased the size to be proper, but when I try to throw in the catalyst, it does nothing. I click the projector and it states, 'no valid recipe'

I tried this in creative in single player and it worked just fine.  Trying to get access to the server to give you more info.

![2017-12-06_20 43 40](https://user-images.githubusercontent.com/20156241/33684466-f9eb90e6-da93-11e7-884b-cb9ef095b05a.png)

**Comment by davenonymous** [comment] 2017-12-06 20:57
Does the server maybe have different recipes configured than the client?

**Comment by deceet** [comment] 2017-12-06 20:59
No, it's literally an exported default setup of mods from multimc, cm3 was added manually and the server was restarted to load it.  I was hoping the recipe unpack and a /reload would fix this, but alas, I wouldn't be that lucky :)

**Comment by davenonymous** [comment] 2017-12-06 21:01
Please check anyway, because it sounds very much like this would be the issue.

**Comment by deceet** [comment] 2017-12-06 21:03
What I'm trying to work, on, I contacted my buddy since he's the only one with access, currently in class I imagine, I will let you know ASAP.

**Comment by deceet** [comment] 2017-12-07 04:54
ok, I did the unpack recipe command prior to the server being rebooted, but a restart fixed the problem, perhaps the mod isn't initializing the recipes on first use, server wise?

**Comment by davenonymous** [comment] 2017-12-17 10:52
You should only do the unpack recipe command if you intend to modify the default recipes, i.e. if you create your own modpack - the recipes on the client and on the server must be the same or you run into this issue.

**Closed as completed by davenonymous** 2017-12-17 10:52 UTC
