### ISSUE TITLE
Endless server-like lag when entering an empty machine (Singleplayer world)

### ISSUE THREAD

**Issue by Ciberbago** [CompactMods/CompactMachines#321] opened 2018-04-27 22:49 UTC
**Compact Machines version**: 1.12.2-3.0.8-b200
(idk if it is a beta version but in the last version happened too)

**Modpack**: Enigmatica 2 Expert
**Forge version**: 14.23.3.2673
**I am not using Optifine**: Without optifine
**Link to Crashlog**: I can't upload a log because the game does not crash, it stays there forever.

But with the minecraft log console says this: 

14:35:22 | FML | Server thread | warn | CoFH World loaded a new chunk [129, -4] in dimension 0 (overworld) while populating chunk [129, -3], causing cascading worldgen lag.
-- | -- | -- | -- | --
14:35:22 | FML | Server thread | warn | Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14:35:27 | net.minecraft.server.MinecraftServer | Server thread | warn | Can't keep up! Did the system time change, or is the server overloaded? Running 11922ms behind, skipping 238 tick(s)

**Screenshot (if possible)**: https://imgur.com/a/j9kwDL5

**Description of the problem including expected versus actual behavior:** I have 2 compact machines of maximum size. With garden cloches and other with only a pulverizer and a furnace. When I tried to do the 3rd one I entered into it and the game lags forever, like in a server (is a singleplayer world). I tried to reproduce this bug in creative but in other world does not happen. I don't know why but if I turn the render distance to 2 chunks before entering the bugged machine it works normally.  And no, my pc is not a potato (i5-6600, 16gb ram with 8gb dedicated to mc, gtx 1050ti). On top of this post I put the log from minecraft console with the warning.

**Steps to reproduce:** As a said the steps are:
Playing a normal SP world, make 3 machines, the third one empty, when you enter it lags.

**Comment by davenonymous** [comment] 2018-04-28 07:58
I guess this is a compatibility issue with some other mod in the pack. I can not reproduce this with Compact Machines alone. No idea which one though. Guesses?

**Comment by davenonymous** [comment] 2018-04-28 08:51
This is actually a duplicate of #316 and a Ice and Fire Mod issue.

**Closed as completed by davenonymous** 2018-04-28 08:51 UTC
