### ISSUE TITLE
Can place blocks outside using building gadget

### ISSUE THREAD

**Issue by Old-Man-D** [CompactMods/CompactMachines#393] opened 2019-04-26 04:31 UTC
I've noticed that using direwolf's building gadget, you can inadvertently place blocks outside of the compact machine, and they will be stuck there.  I was using mine to paste on all the inside faces of my compact machines.  I suspect that when doing the ceiling, the gadget is attemping to complete my range (if set too high), and that it must be skipping something like barrier blocks that are closer to the outer walls, but probably only 3 blocks thick judging by the map.  Both the building gadget and the exchanging gadget will do this.  No crashes are occurring because of this.

Enigmatica 2 Expert, V1.62
Compact machines V3.0.17-b267
Forge V14.23.5.2781
building gadget V2.6.8

https://imgur.com/gallery/SzMyBNY

**Comment by SashaGelert** [comment] 2020-08-15 22:26
Compact Machines are technically in a Void dimension, there is nothing naturally outside preventing block placement, and even further if the CM3 config isn't set to keep players inside the machines, most forms of short-range teleportation can be used to gain rooftop access and build anything you please. I like it personally as it is a good alternative to not having RFTools or Mystcraft installed (and thus no easy void dimension for base building).

**Comment by robotgryphon** [comment] 2021-01-16 14:00
Going to close this one as "working as intended" since Building Gadgets offers easy undo functionality to save yourself from this problem. We'd have to add a bunch of extra code in place to scan for blocks otherwise, which is a drain on server resources. Easier to just undo the operation.

**Closed as completed by robotgryphon** 2021-01-16 14:00 UTC
