### ISSUE TITLE
Wrong Compact Machine Size

### ISSUE THREAD

**Issue by bubbaboogs** [CompactMods/CompactMachines#516] opened 2022-05-17 00:08 UTC
### I am not using performance mods.

- [X] Confirm

### Description

I made a 3x3x3 Compact Machine, and when I went in my maximum Compact Machine, it spawned me in the 3x3x3. (In ATM7 if it helps)

### Mod Version

4.2.0

### Forge Version

1.18.2 - 40.1.20

### How to reproduce

1. Craft Compact Machine
2.Go inside of Compact Machine
3.Craft bigger Compact Machine
4.Go in bigger Compact Machine

**Comment by robotgryphon** [comment] 2022-05-17 10:22
Duplicate of #513

**Closed as completed by robotgryphon** 2022-05-17 10:22 UTC
