### ISSUE TITLE
Compact Machines Not Working With Small World Borders

### ISSUE THREAD

**Issue by Riewest** [CompactMods/CompactMachines#503] opened 2022-01-16 22:52 UTC
### I am not using performance mods.

- [X] Confirm

### Description

I am hosting/playing a small ATM7 server with a world border set to 1,000 x 1,000 Blocks. 

When a non creative player attempts to enter a compact machine they get teleported out instantly to be within the bounds of the world border and fall into the void. If I enter in Creative mode this does not happen.

Reproduced in Single player by placing several machines down both with and without the world border set to 1000.

### Mod Version

4.0.0 beta 4

### Forge Version

1.18.1 - 39.0.20

### How to reproduce

1. Load into a world
2. Set world border to a 1000 or less   **/worldborder set 1000**
3. Place a compact machine (Tested with Giant and Maximum Sized Machines)
4. Enter in Survival Mode  **/gamemode survival**
5. Repeat without the world border set to a larger value

**Comment by robotgryphon** [comment] 2022-05-28 05:25
See release notes for v4.3.0, should close this issue. Please reach out on Discord or reopen the issue if the problem is not resolved.

**Closed as completed by robotgryphon** 2022-05-28 05:25 UTC
Labels: verified, 18.x

**Comment by tgstyle** [comment] 2023-07-04 22:16
I am using 1.19.2-v5.1.0 and this problem appears to have returned? I have a really low world border (384), enter the machine and it starts acts like I am poisoned and I cannot place anything.

**Comment by Riewest** [comment] 2023-07-05 00:19
> I am using 1.19.2-v5.1.0 and this problem appears to have returned? I have a really low world border (384), enter the machine and it starts acts like I am poisoned and I cannot place anything.

This doesn't quite seem like the same issue and I wasn't able to reproduce it.

### I just threw together a fresh curseforge instance with the following:
Minecraft: `1.19.2`
Forge: `43.2.0`
CompactMachines: `5.1.0`
(As well as latest JEI, Journeymap, Controlling, and Mouse Tweaks)

### I did the following:
1. Create New world (With allow cheats, but in survival)
2. `/worldborder set 384` (Also did 100)
3. Place new Compact machine (Giant)

And it worked fine. 

Seems like the issue you are describing is related more to this feature that was merged: #534
and might be worthy of a new issue if you can reproduce it in a new world.

**Comment by tgstyle** [comment] 2023-07-05 01:28
Appears to be related to doing a flat world, odd thing is in single player you cannot even teleport to the CM dimension, you place the machine and nothing... On a server it teleports you in but you cannot do anything, get poison effect, then eventually you get teleported outside of it.
